### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by husnuumus** [theShadow89/nifi-bigquery-bundle#2]
"mvn clean install" command fails because of inconsistent version of the nifi-bigquery-processors dependency in the pom file of the nifi-bigquery-nar module. The part below causes an error and compilation fails.

<dependency>
            <groupId>org.apache.nifi</groupId>
            <artifactId>nifi-bigquery-processors</artifactId>
            <version>0.1-SNAPSHOT</version>
        </dependency>

To fix the issue just remove the "-SNAPSHOT" part from the version.

**Comment by DediBar** [comment]
Great point

**Comment by theShadow89** [comment]
Now should be fixed
